### ISSUE TITLE
Toggle for dark mod

### ISSUE THREAD

**Issue by OfficialMarinho** [Rocketseat/gatsby-themes#19] opened 2020-07-19 23:46 UTC
**What would you like to be added**:
A toggle into the menu to change the currently set color.

**Why is this needed**:
Accessibility and more design options.

**Is your enhancement request related to a problem? Please describe.**
Documentation with light colors at night can damage your eyesight.

**Additional context**

**Comment by jpedroschmitz** [comment] 2020-07-21 22:33
This issue is a duplicate of #16.

**Closed by jpedroschmitz** 2020-07-21 22:33 UTC
Labels: enhancement
